### ISSUE TITLE
Deployment Loop and "workaround".

### ISSUE THREAD

**Issue by famewolf** [dmzoneill/lidarr-youtube-downloader#11]
I received this error before the recent mod to use yt-dlp as well as after.  Previously you could make the error go away by pointing the app to a new directory where no music was present.   In this case the only thing in lidarr's wanted list is Kelly Clarkson's Breakway album and although a "Breakaway (2018) folder exists lyd creates a "Breakaway" folder so not sure why it's occuring.  

The workaround is to point lyd to a subdir of the music folder then import those tracks.

2023-05-10 14:46:17.400667+00:00Starting Lidarr Youtube Downloader
2023-05-10 14:46:17.500630+00:00Album: 1/1   Track: 1/19
2023-05-10 14:46:17.500695+00:00================================================================================
2023-05-10 14:46:17.500703+00:002023-05-10T14:46:17.500703917Z
2023-05-10 14:46:17.500708+00:00Path           : /mnt/tank/shared/media/music/Kelly Clarkson
2023-05-10 14:46:17.500722+00:00Artist         : Kelly Clarkson
2023-05-10 14:46:17.500727+00:00Album          : Breakaway
2023-05-10 14:46:17.500731+00:00Track          : Breakaway
2023-05-10 14:46:17.500736+00:00Genre          : Alternative Rock
2023-05-10 14:46:17.500740+00:00Date           : 2004
2023-05-10 14:46:17.500748+00:00CD Count       : 1
2023-05-10 14:46:17.500753+00:00CD No          : 1
2023-05-10 14:46:17.500757+00:00Track No       : 1/15
2023-05-10 14:46:17.500761+00:002023-05-10T14:46:17.500761919Z
2023-05-10 14:46:17.511525+00:00Traceback (most recent call last):
2023-05-10 14:46:17.511561+00:002023-05-10T14:46:17.511561964Z
2023-05-10 14:46:17.511578+00:00File "/lyd.py", line 605, in <module>
2023-05-10 14:46:17.511585+00:00app()
2023-05-10 14:46:17.511589+00:002023-05-10T14:46:17.511589954Z
2023-05-10 14:46:17.511594+00:00File "/lyd.py", line 601, in run
2023-05-10 14:46:17.511598+00:00iterate_missing(artist, iterative)
2023-05-10 14:46:17.511607+00:002023-05-10T14:46:17.511607973Z
2023-05-10 14:46:17.511612+00:00File "/lyd.py", line 572, in iterate_missing
2023-05-10 14:46:17.511617+00:00iterate_records(json["records"], totalRecords, record_counter, artist_filter)
2023-05-10 14:46:17.511622+00:002023-05-10T14:46:17.511622688Z
2023-05-10 14:46:17.511627+00:00File "/lyd.py", line 526, in iterate_records
2023-05-10 14:46:17.511635+00:00iterate_tracks(
2023-05-10 14:46:17.511640+00:002023-05-10T14:46:17.511640188Z
2023-05-10 14:46:17.511644+00:00File "/lyd.py", line 498, in iterate_tracks
2023-05-10 14:46:17.511648+00:00get_song(
2023-05-10 14:46:17.511653+00:002023-05-10T14:46:17.511653099Z
2023-05-10 14:46:17.511657+00:00File "/lyd.py", line 371, in get_song
2023-05-10 14:46:17.511664+00:00update_lidarr_db(artistName, albumName, title, trackNumber, year)
2023-05-10 14:46:17.511669+00:002023-05-10T14:46:17.511669592Z
2023-05-10 14:46:17.511674+00:00File "/lyd.py", line 293, in update_lidarr_db
2023-05-10 14:46:17.511678+00:00album_id = get_lidarr_album_id(cur, albumName, year)
2023-05-10 14:46:17.511686+00:002023-05-10T14:46:17.511686155Z
2023-05-10 14:46:17.511690+00:00File "/lyd.py", line 236, in get_lidarr_album_id
2023-05-10 14:46:17.511694+00:00cur.execute(
2023-05-10 14:46:17.511699+00:002023-05-10T14:46:17.511699545Z
2023-05-10 14:46:17.511703+00:00sqlite3.OperationalError: no such table: Albums
2023-05-10 14:46:17.511708+00:002023-05-10T14:46:17.511708083Z

![image](https://github.com/dmzoneill/lidarr-youtube-downloader/assets/4558832/0afc5ab7-43a3-47ee-892a-fdca8410b31f)
![image](https://github.com/dmzoneill/lidarr-youtube-downloader/assets/4558832/0e1baf61-31b1-4273-9690-4c79823dee88)

**Comment by famewolf** [comment]
Workaround is NOT working this time..even when pointed to empty subdir after creating the Kelly Clarkson folder and Breakaway  folder it gives same error.

![image](https://github.com/dmzoneill/lidarr-youtube-downloader/assets/4558832/71863fa6-b4a4-4be8-9d63-ef83c541ce69)


2023-05-10 15:08:54.798791+00:00Starting Lidarr Youtube Downloader
2023-05-10 15:08:54.925174+00:00Album: 1/1   Track: 1/19
2023-05-10 15:08:54.925201+00:00================================================================================
2023-05-10 15:08:54.925208+00:002023-05-10T15:08:54.925208408Z
2023-05-10 15:08:54.925213+00:00Path           : /mnt/tank/shared/media/music/Kelly Clarkson
2023-05-10 15:08:54.925226+00:00Artist         : Kelly Clarkson
2023-05-10 15:08:54.925231+00:00Album          : Breakaway
2023-05-10 15:08:54.925237+00:00Track          : Breakaway
2023-05-10 15:08:54.925246+00:00Genre          : Alternative Rock
2023-05-10 15:08:54.925252+00:00Date           : 2004
2023-05-10 15:08:54.925260+00:00CD Count       : 1
2023-05-10 15:08:54.925265+00:00CD No          : 1
2023-05-10 15:08:54.925270+00:00Track No       : 1/15
2023-05-10 15:08:54.925274+00:002023-05-10T15:08:54.925274786Z
2023-05-10 15:08:55.960312+00:00Youtube search
2023-05-10 15:08:55.960391+00:00========================================
2023-05-10 15:08:55.960431+00:002023-05-10T15:08:55.960431833Z
2023-05-10 15:08:55.960447+00:00Best title: Kelly Clarkson - Breakaway (VIDEO)
2023-05-10 15:08:55.960460+00:00Best match: 0.8666666666666667
2023-05-10 15:08:55.960474+00:002023-05-10T15:08:55.960474090Z
2023-05-10 15:08:55.960487+00:00Selected https://www.youtube.com/watch?v=c-3vPxKdj6o
2023-05-10 15:08:55.960511+00:002023-05-10T15:08:55.960511155Z
2023-05-10 15:08:55.960532+00:00Youtube-dl
2023-05-10 15:08:55.960546+00:00========================================
2023-05-10 15:08:55.960561+00:002023-05-10T15:08:55.960561120Z
2023-05-10 15:08:55.960574+00:00youtube-dl
2023-05-10 15:08:55.960611+00:00--no-progress
2023-05-10 15:08:55.960624+00:00-x
2023-05-10 15:08:55.960637+00:00--audio-format mp3 "https://www.youtube.com/watch?v=c-3vPxKdj6o"
2023-05-10 15:08:55.960685+00:00-o 
2023-05-10 15:08:55.960693+00:00"/music/Kelly Clarkson/Breakaway/Kelly Clarkson - Breakaway - Breakaway.mp3"
2023-05-10 15:08:55.960703+00:002023-05-10T15:08:55.960703997Z
2023-05-10 15:09:02.794978+00:002023-05-10T15:09:02.794978746Z
2023-05-10 15:09:02.795028+00:00Downloaded successfully
2023-05-10 15:09:02.795042+00:002023-05-10T15:09:02.795042079Z
2023-05-10 15:09:02.795050+00:00[youtube] Extracting URL: https://www.youtube.com/watch?v=c-3vPxKdj6o
2023-05-10 15:09:02.795074+00:00[youtube] c-3vPxKdj6o: Downloading webpage
2023-05-10 15:09:02.795093+00:00[youtube] c-3vPxKdj6o: Downloading android player API JSON
2023-05-10 15:09:02.795102+00:00[info] c-3vPxKdj6o: Downloading 1 format(s): 251
2023-05-10 15:09:02.795109+00:00[dashsegments] Total fragments: 1
2023-05-10 15:09:02.795123+00:00[download] Destination: /music/Kelly Clarkson/Breakaway/Kelly Clarkson - Breakaway - Breakaway.webm
2023-05-10 15:09:02.795130+00:00[download] Download completed
2023-05-10 15:09:02.795137+00:00[ExtractAudio] Destination: /music/Kelly Clarkson/Breakaway/Kelly Clarkson - Breakaway - Breakaway.mp3
2023-05-10 15:09:02.795144+00:00Deleting original file /music/Kelly Clarkson/Breakaway/Kelly Clarkson - Breakaway - Breakaway.webm (pass -k to keep)
2023-05-10 15:09:02.795156+00:002023-05-10T15:09:02.795156719Z
2023-05-10 15:09:02.808708+00:00Traceback (most recent call last):
2023-05-10 15:09:02.808738+00:002023-05-10T15:09:02.808738382Z
2023-05-10 15:09:02.808758+00:00File "/lyd.py", line 605, in <module>
2023-05-10 15:09:02.808775+00:00app()
2023-05-10 15:09:02.808781+00:002023-05-10T15:09:02.808781301Z
2023-05-10 15:09:02.808787+00:00File "/lyd.py", line 601, in run
2023-05-10 15:09:02.808796+00:00iterate_missing(artist, iterative)
2023-05-10 15:09:02.808808+00:002023-05-10T15:09:02.808808269Z
2023-05-10 15:09:02.808814+00:00File "/lyd.py", line 572, in iterate_missing
2023-05-10 15:09:02.808823+00:00iterate_records(json["records"], totalRecords, record_counter, artist_filter)
2023-05-10 15:09:02.808829+00:002023-05-10T15:09:02.808829180Z
2023-05-10 15:09:02.808834+00:00File "/lyd.py", line 526, in iterate_records
2023-05-10 15:09:02.808839+00:00iterate_tracks(
2023-05-10 15:09:02.808843+00:002023-05-10T15:09:02.808843688Z
2023-05-10 15:09:02.808857+00:00File "/lyd.py", line 498, in iterate_tracks
2023-05-10 15:09:02.808863+00:00get_song(
2023-05-10 15:09:02.808868+00:002023-05-10T15:09:02.808868053Z
2023-05-10 15:09:02.808872+00:00File "/lyd.py", line 441, in get_song
2023-05-10 15:09:02.808877+00:00append_to_skip_file(bestLink)
2023-05-10 15:09:02.808886+00:002023-05-10T15:09:02.808886165Z
2023-05-10 15:09:02.808891+00:00File "/lyd.py", line 333, in append_to_skip_file
2023-05-10 15:09:02.808896+00:00with open(".skip", "a+") as file_object:
2023-05-10 15:09:02.808901+00:002023-05-10T15:09:02.808901409Z
2023-05-10 15:09:02.808906+00:00PermissionError: [Errno 13] Permission denied: '.skip'
2023-05-10 15:09:02.808914+00:002023-05-10T15:09:02.808914313Z

**Comment by famewolf** [comment]
Ok I caused the last one because I changed the container to run as a specific user and it didn't like it so error still occurs but workaround DOES still work.
