### ISSUE TITLE
pip installation fails on Raspberry Pi: EntryPoint must be in 'name=module:attrs [extras]' format", 'lyd-unmapped=lidarr_youtube_downloader.lyd-unmapped:app 

### ISSUE THREAD

**Issue by guerda** [dmzoneill/lidarr-youtube-downloader#17]
A pip install fails with the following error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2936, in get_entry_map
    ep_map = self._ep_map
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2902, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 452, in run
    installed = install_given_reqs(
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 847, in install
    install_wheel(
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
    _install_wheel(
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 565, in _install_wheel
    console, gui = get_entrypoints(distribution)
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py", line 121, in get_entrypoints
    for entry_point in dist.iter_entry_points():
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_internal/metadata/pkg_resources.py", line 190, in iter_entry_points
    for group, entries in self._dist.get_entry_map().items():
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2938, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2610, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2588, in parse_group
    ep = cls.parse(line, dist)
  File "/home/pi/.local/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2566, in parse
    raise ValueError(msg, src)
ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'lyd-unmapped=lidarr_youtube_downloader.lyd-unmapped:app')

```

# Environment:

* Raspberry Pi 4 B, armhf 64, bookworm
* Python 3.9.2, pip 23.3.1

**Comment by dmzoneill** [comment]
ill take a look at this soon.  Apologies for the delay

**Comment by guerda** [comment]
Removing the entrypoint from `setup.py` worked for me just fine.
